module.exports = [
    'Salesópolis',
    'Biritiba Mirim',
    'Mogi das Cruzes',
    'Suzano',
    'Itaquaquecetuba',
    'São Paulo',
    'Osasco',
    'Barueri',
    'Santana de Parnaíba',
    'Pirapora do Bom Jesus',
    'Cabreúva',
    'Salto',
    'Itu',
    'Porto Feliz',
    'Tietê',
    'Laranjal Paulista',
    'Conchas',
    'Anhembi',
    'São Manuel',
    'Mineiros do Tietê',
    'Macatuba',
    'Igaraçu do Tietê',
    'Barra Bonita',
    'Jaú',
    'Pederneiras',
    'Itapuí',
    'Boracéia',
    'Bariri',
    'Itaju',
    'Arealva',
    'Ibitinga',
    'Iacanga',
    'Reginópolis',
    'Pongaí',
    'Borborema',
    'Cafelândia',
    'Novo Horizonte',
    'Sabino',
    'Sales',
    'Promissão',
    'Adolfo',
    'José Bonifácio',
    'Ubarana',
    'Barbosa',
    'Penápolis',
    'Zacarias',
    'Buritama',
    'Birigüi',
    'Araçatuba',
    'Santo Antônio do Aracanguá',
    'Sud Menucci',
    'Pereira Barreto',
    'Andradina',
    'Castilho',
    'Itapura',
];